### ISSUE TITLE
Handle rejected promise

### ISSUE THREAD

**Issue by cod3beat** [dicodingacademy/a219-mfwde-labs#1]
https://github.com/dicodingacademy/a219-mfwde-labs/blob/8a8f01bc5dd6b06ddb1dde89998f16da845ab84d/movie-catalogue/src/scripts/views/pages/now-playing.js#L17

Disini apa kita tidak perlu memeriksa bila promisenya rejected ya? Misalnya tokennya salah, dsb

**Comment by thesyamsulzaman** [comment]
Pake try catch kak, biar rejected promisenya kehandle
